// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Chats = sequelize.define('chats', {
    fromType: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    fromId: {
      type: DataTypes.BIGINT,
      allowNull: false,
    },
    toType: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    toId: {
      type: DataTypes.BIGINT,
      allowNull: false,
    },
    channel: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    blockedAt: {
      type: DataTypes.DATE,
    },
    deletedAt: {
      type: DataTypes.DATE,
    },
    createdAt: {
      type: DataTypes.DATE,
    },
    updatedAt: {
      type: DataTypes.DATE,
    },
  }, {
    tableName: 'chats',
    underscored: true,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Chats.associate = (models) => {
    Chats.belongsTo(models.users, {
      foreignKey: {
        name: 'blockedByUserIdKey',
        field: 'blocked_by_user_id',
      },
      as: 'blockedByUser',
    });
    Chats.hasMany(models.chatUser, {
      foreignKey: {
        name: 'chatIdKey',
        field: 'chat_id',
      },
      as: 'chatUsers',
    });
  };

  return Chats;
};
