// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const HealthChecks = sequelize.define('healthChecks', {
    resourceName: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    resourceSlug: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    targetName: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    targetSlug: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    targetDisplay: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    healthy: {
      type: DataTypes.INTEGER,
      allowNull: false,
    },
    errorMessage: {
      type: DataTypes.STRING,
    },
    value: {
      type: DataTypes.STRING,
    },
    valueHuman: {
      type: DataTypes.STRING,
    },
    createdAt: {
      type: DataTypes.DATE,
    },
  }, {
    tableName: 'health_checks',
    underscored: true,
    timestamps: false,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  HealthChecks.associate = (models) => {
  };

  return HealthChecks;
};
