// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Invoices = sequelize.define('invoices', {
    ownerType: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    ownerId: {
      type: DataTypes.BIGINT,
      allowNull: false,
    },
    from: {
      type: DataTypes.DATE,
      allowNull: false,
    },
    to: {
      type: DataTypes.DATE,
      allowNull: false,
    },
    transactions: {
      type: DataTypes.JSON,
      allowNull: false,
    },
    approvedAt: {
      type: DataTypes.DATE,
    },
    amount: {
      type: DataTypes.DOUBLE,
      allowNull: false,
    },
    pdfPath: {
      type: DataTypes.STRING,
    },
    deletedAt: {
      type: DataTypes.DATE,
    },
    createdAt: {
      type: DataTypes.DATE,
    },
    updatedAt: {
      type: DataTypes.DATE,
    },
  }, {
    tableName: 'invoices',
    underscored: true,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Invoices.associate = (models) => {
    Invoices.belongsTo(models.users, {
      foreignKey: {
        name: 'approvedByUserIdKey',
        field: 'approved_by_user_id',
      },
      as: 'approvedByUser',
    });
    Invoices.belongsTo(models.bankAccounts, {
      foreignKey: {
        name: 'bankAccountIdKey',
        field: 'bank_account_id',
      },
      as: 'bankAccount',
    });
    Invoices.belongsTo(models.currencies, {
      foreignKey: {
        name: 'currencyIdKey',
        field: 'currency_id',
      },
      as: 'currency',
    });
    Invoices.belongsTo(models.transactions, {
      foreignKey: {
        name: 'transactionIdKey',
        field: 'transaction_id',
      },
      as: 'transaction',
    });
  };

  return Invoices;
};
