// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const JobBatches = sequelize.define('jobBatches', {
    id: {
      type: DataTypes.STRING,
      primaryKey: true,
      allowNull: false,
    },
    name: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    totalJobs: {
      type: DataTypes.INTEGER,
      allowNull: false,
    },
    pendingJobs: {
      type: DataTypes.INTEGER,
      allowNull: false,
    },
    failedJobs: {
      type: DataTypes.INTEGER,
      allowNull: false,
    },
    failedJobIds: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    options: {
      type: DataTypes.STRING,
    },
    cancelledAt: {
      type: DataTypes.INTEGER,
    },
    createdAt: {
      type: DataTypes.INTEGER,
      allowNull: false,
    },
    finishedAt: {
      type: DataTypes.INTEGER,
    },
  }, {
    tableName: 'job_batches',
    underscored: true,
    timestamps: false,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  JobBatches.associate = (models) => {
  };

  return JobBatches;
};
