// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const PlanPrices = sequelize.define('planPrices', {
    price: {
      type: DataTypes.DOUBLE,
      allowNull: false,
    },
    activeAt: {
      type: DataTypes.DATE,
    },
    deactivateAt: {
      type: DataTypes.DATE,
    },
    createdAt: {
      type: DataTypes.DATE,
    },
    updatedAt: {
      type: DataTypes.DATE,
    },
    deletedAt: {
      type: DataTypes.DATE,
    },
  }, {
    tableName: 'plan_prices',
    underscored: true,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  PlanPrices.associate = (models) => {
    PlanPrices.belongsTo(models.plans, {
      foreignKey: {
        name: 'planIdKey',
        field: 'plan_id',
      },
      as: 'plan',
    });
    PlanPrices.belongsTo(models.currencies, {
      foreignKey: {
        name: 'currencyIdKey',
        field: 'currency_id',
      },
      as: 'currency',
    });
    PlanPrices.hasMany(models.subscriptions, {
      foreignKey: {
        name: 'planPriceIdKey',
        field: 'plan_price_id',
      },
      as: 'planPriceSubscriptions',
    });
  };

  return PlanPrices;
};
