// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const TaxRefunds = sequelize.define('taxRefunds', {
    source: {
      type: DataTypes.STRING,
    },
    relationType: {
      type: DataTypes.STRING,
    },
    relationId: {
      type: DataTypes.BIGINT,
    },
    totalKwh: {
      type: DataTypes.DOUBLE,
      allowNull: false,
    },
    diffKwh: {
      type: DataTypes.DOUBLE,
      allowNull: false,
    },
    amountPerKwh: {
      type: DataTypes.DOUBLE,
      allowNull: false,
    },
    amount: {
      type: DataTypes.DOUBLE,
      allowNull: false,
    },
    deletedAt: {
      type: DataTypes.DATE,
    },
    createdAt: {
      type: DataTypes.DATE,
    },
    updatedAt: {
      type: DataTypes.DATE,
    },
  }, {
    tableName: 'tax_refunds',
    underscored: true,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  TaxRefunds.associate = (models) => {
    TaxRefunds.belongsTo(models.currencies, {
      foreignKey: {
        name: 'currencyIdKey',
        field: 'currency_id',
      },
      as: 'currency',
    });
    TaxRefunds.belongsTo(models.subscriptions, {
      foreignKey: {
        name: 'subscriptionIdKey',
        field: 'subscription_id',
      },
      as: 'subscription',
    });
  };

  return TaxRefunds;
};
